### PR TITLE
Update FormBlock.php

### PR DESCRIPTION
**Pull request by jerrynavi**
Translated from German to English

### CODE REVIEW

**Comment by nadar** [comment]
@jerryasih Thanks for the PR. Maybe someone should make a repository for a form block, as i think this block is not a very good solution as its heavily limited. Someone had the idea to make forms with blocks => https://github.com/luyadev/luya/issues/1541

And it should contain translations from the message system.

**Comment by nadar** [comment]
@luyadev/coredev

**Comment by jerrynavi** [comment]
I already thought about making a form block using bootstrap4 and I've seen this: [luyadev/luya#1541](https://github.com/luyadev/luya/issues/1541)
Is anyone working on that at the moment? My solution would have been equally limited/specific to my application.

**Review by nadar — CHANGES_REQUESTED** [review]
Almost forgot. Could you please add a changelog entry?

**Comment by nadar** [comment]
@jerryasih currently there are just plans about doing some form builder for bootstrap 4 but no one started yet. I think it should be a block with a placeholder which generates the form (ActiveForm) and then some input controls to drag into. Should not be to heavy.

**Comment by jerrynavi** [comment]
Hi @nadar, how do I add a changelog entry?

**Comment by nadar** [comment]
Just described what you did with reference to this PR (so the other example from 1.0.1) here: https://github.com/luyadev/luya-bootstrap3/blob/master/CHANGELOG.md

**Review by jerrynavi — COMMENTED** [review]
Updated CHANGELOG.md

**Comment by nadar** [comment]
@jerryasih perfect, thanks!

**Pull request merged**
